name: Windows Python CI for Sentiment Stock Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.13.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        } else {
          pip install pandas yfinance textblob jupyter scikit-learn matplotlib seaborn talib-binary flake8
        }

    - name: Download NLTK data (if using NLTK)
      run: |
        python -m nltk.downloader punkt vader_lexicon

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting completed with warnings"

    - name: Run notebooks
      run: |
        pip install nbconvert
        jupyter nbconvert --execute notebooks/*.ipynb --to notebook --output executed_notebook.ipynb

    - name: Run unit tests
      run: |
        if (Test-Path "tests") {
          python -m unittest discover -s tests
        } else {
          echo "No tests/ directory found. Skipping tests."
        }
